import jsPDF from 'jspdf'
import autoTable from 'jspdf-autotable'

interface StaffShift {
  staffName: string
  role: string
  shifts: { day: string; shiftName: string; time?: string; notes?: string }[]
}

interface DayArrival {
  date: string
  count: number
  isHeavy: boolean
}

export async function exportScheduleToPDF(
  weekStartDate: string,
  weekEndDate: string,
  staffShifts: StaffShift[],
  arrivals: DayArrival[],
  hotelName: string = 'THEO Mini Hotel'
) {
  const doc = new jsPDF('landscape', 'mm', 'a4')
  const pageWidth = doc.internal.pageSize.getWidth()
  
  // Title
  doc.setFontSize(18)
  doc.setTextColor(40, 40, 80)
  doc.text(`${hotelName} - Weekly Staff Schedule`, pageWidth / 2, 15, { align: 'center' })
  
  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Week of ${new Date(weekStartDate).toLocaleDateString()} to ${new Date(weekEndDate).toLocaleDateString()}`, pageWidth / 2, 25, { align: 'center' })
  
  // Arrivals summary table
  const arrivalsData = arrivals.map(a => [
    new Date(a.date).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }),
    a.count.toString(),
    a.isHeavy ? '⚠️ Heavy' : ''
  ])
  
  autoTable(doc, {
    startY: 35,
    head: [['Date', 'Expected Arrivals', 'Note']],
    body: arrivalsData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [240, 248, 255] },
    margin: { left: 14, right: 14 },
  })
  
  // Staff schedule table
  const tableHeaders = ['Staff Name', 'Role', ...arrivals.map(a => new Date(a.date).toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }))]
  
  const tableBody = staffShifts.map(staff => {
    const row = [staff.staffName, staff.role]
    for (const arrival of arrivals) {
      const shiftForDay = staff.shifts.find(s => s.day === arrival.date)
      let cellContent = shiftForDay ? `${shiftForDay.shiftName}${shiftForDay.time ? `\n${shiftForDay.time}` : ''}` : '—'
      if (shiftForDay?.notes) {
        cellContent += `\n📝 ${shiftForDay.notes.slice(0, 30)}`
      }
      row.push(cellContent)
    }
    return row
  })
  
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [tableHeaders],
    body: tableBody,
    theme: 'striped',
    headStyles: { fillColor: [46, 125, 50], textColor: 255, fontStyle: 'bold' },
    columnStyles: {
      0: { cellWidth: 35 },
      1: { cellWidth: 25 },
    },
    styles: { fontSize: 9, cellPadding: 2, overflow: 'linebreak' },
    margin: { left: 14, right: 14 },
  })
  
  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(`Generated by THEO Mini - ${new Date().toLocaleString()}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })
  }
  
  doc.save(`THEO_Schedule_${new Date(weekStartDate).toISOString().slice(0,10)}.pdf`)
}